nginx:
  container_name: nginx
  build: ./nginx
  env_file:
    - './.env'
  volumes:
    - ./nginx/default.crt:/srv/config/fullchain.pem
    - ./nginx/default.key:/srv/config/privkey.pem
  volumes_from:
#    - letsencrypt
    - php
  ports:
    - '80:80'
    - '443:443'

php:
  build: ./php
  volumes:
    - /php
    - /srv/www

mysql:
  container_name: mysql
  image: mariadb:latest
    env_file:
    - './.env'
  environment:
    MYSQL_ROOT_PASSWORD: 'CHANGEME'
    MYSQL_DATABASE: 'pydio'
    MYSQL_USER: 'pydio'
    MYSQL_PASSWORD: 'CHANGEME'
  expose:
    - '3306'

#letsencrypt:
#  container_name: letsencrypt
#  build: ./letsencrypt
#  volumes:
#      - ./persistent/letsencrypt:/etc/letsencrypt
#      - /var/lib/letsencrypt
#      - /srv/letsencrypt-webrootauth
#  command: root certonly --email CHANGEME@gmail.com -d CHANGEME.com -d www.CHANGEME.com --renew-by-default -a webroot --webroot-path /srv/letsencrypt-webrootauth --text --agree-tos --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory
